<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>SteamWorkshopUploader</AssemblyName>
    <RootNamespace>SteamWorkshopUploader</RootNamespace>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <PropertyGroup>
    <GameBin>C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client</GameBin>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Steamworks.NET">
      <HintPath>$(GameBin)\Steamworks.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <Target Name="SteamApiKopyala" AfterTargets="Build">
    <Copy SourceFiles="$(GameBin)\steam_api64.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" ContinueOnError="true" />
    <WriteLinesToFile File="$(OutDir)steam_appid.txt" Lines="261550" Overwrite="true" />
  </Target>

</Project>
